productVersion: 2.6.0
image:
  tag: v1.3.9
  pullPolicy: IfNotPresent
persistentVolume:
  pvEnabled: false
  pvcEnabled: true
  mountToSubPath: repository/deployment/server/synapse-configs
  accessMode: ReadWriteMany
  storageClass: ${storage_class_name}
readinessProbe:
  enabled: true
  initialDelaySeconds: 150
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
ingress:
  mgmt:
    internal: 
      enabled: true
      annotations:
        kubernetes.io/ingress.class: ${int_ingress_controller_name}
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        
      hosts:
        - host: ${mgmt_int_host}
          paths:
            - path: "/"
              servicePort: wso2
      tls:
        - secretName: ""
          hosts:
            - ${mgmt_int_host}
    external: 
      enabled: false
  data:
    external:
      enabled: false
    internal:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: ${int_ingress_controller_name}
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        
      hosts:
        - host: ${data_int_host}
          paths:
            - path: "/"
              servicePort: wso2https
      tls:
        - secretName: ""
          hosts:
            - ${data_int_host}
service:
  type: ClusterIP
  ports:
    wso2:
      name: wso2
      externalPort: 9443
      internalPort: 32443
      targetPort: 9443
    wso2https:
      name: wso2https
      externalPort: 8243
      internalPort: 32244
      targetPort: 8243
      enabled: true
  sessionAffinity: 
    enabled: true
    affinityType: ClientIP
secret:
  externalSecretVolMountEnabled: true
  wso2amSecretVolPath: /home/wso2carbon/wso2-secret-volume
  externalSecretName: wso2am-secret
configmap:
  externalConfigMapVolMountEnabled: true
  wso2amConfigVolPath: /home/wso2carbon/wso2-config-volume
  externalConfigMapName: wso2am-confmap
binconfigmap:
  externalConfigMapVolMountEnabled: true
  externalConfigMapName: wso2am-binmap
