productVersion: 2.6.0
image:
  tag: v1.3.9
  pullPolicy: IfNotPresent
persistentVolume:
  pvEnabled: false
  pvcEnabled: true
  mountToSubPath: repository/deployment/server/synapse-configs
  accessMode: ReadWriteMany
  storageClass: efs
readinessProbe:
  enabled: true
  initialDelaySeconds: 150
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
ingress:
  apiServer:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      cert-manager.io/cluster-issuer: letsencrypt
      
    hosts:
      - host: ${ingress_host}
        paths:
          - path: "/"
            servicePort: wso2
    tls:
      - secretName: intgw-tls
        hosts:
          - ${ingress_host}
  tokenServer:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      cert-manager.io/cluster-issuer: letsencrypt
      
    hosts:
      - host: ${token_ingress_host}
        paths:
          - path: "/"
            servicePort: wso2https
    tls:
      - secretName: tokenintgw-tls
        hosts:
          - ${token_ingress_host}
service:
  type: ClusterIP
  ports:
    wso2:
      name: wso2
      externalPort: 9443
      internalPort: 32443
      targetPort: 9443
    wso2https:
      name: wso2https
      externalPort: 8243
      internalPort: 32244
      targetPort: 8243
      enabled: true
  sessionAffinity: 
    enabled: true
    affinityType: ClientIP
secret:
  externalSecretVolMountEnabled: true
  wso2amSecretVolPath: /home/wso2carbon/wso2-secret-volume
  externalSecretName: wso2am-secret
configmap:
  externalConfigMapVolMountEnabled: true
  wso2amConfigVolPath: /home/wso2carbon/wso2-config-volume
  externalConfigMapName: wso2am-confmap
binconfigmap:
  externalConfigMapVolMountEnabled: true
  externalConfigMapName: wso2am-binmap
