[template]
src = "whitelist_extgw.tmpl"
dest = "/etc/haproxy/whitelist_extgw"
uid = 0
gid = 0
mode = "0644"
keys = [
  "whitelist_fsps",
  "whitelist_pm4mls",
  "whitelist_nat",
  "whitelist_addons",
  "whitelist_vpn",
  "whitelist_gateway",
  "whitelist_sims"
]
#check_cmd = "haproxy check new config  {{.src}}" - Might be handy in the future but not for now
reload_cmd = "/etc/init.d/haproxy reload"
