- name: Create GitLab User
  hosts: localhost
  gather_facts: false
  vars:
    password: changeme123
  tasks:
    - name: Add user to Gitlab
      gitlab_user:
        api_url: "{{ gitlab_url }}"
        api_token: "_W3Te4KN_RTt2D-J1y-e"
        name: "{{ item.name }}"
        username: "{{ item.username }}"
        password: "{{ password }}"
        email: "{{ item.email}}"
        state: present
        group: infrastructure
        access_level: maintainer
        isadmin: yes
        confirm: no
      delegate_to: localhost
      tags: add
      loop: "{{ users }}"
