{{- range $key, $value := $.Values.secretKeyMap }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: '{{ $.Values.secretName }}-{{ $key }}'
  namespace: {{ $.Values.namespace }}
spec:
  authentication: 
    path: {{ $.Values.authPath }}
    role: {{ $.Values.authRole }}
    serviceAccount:
      name: {{ $.Values.authSvcAcct }}
  isKVSecretsEngineV2: false
  path: "{{ $.Values.vaultBasePath }}/{{ $.Values.resourceName }}"
  secretKey: password
  secretFormat:
    passwordPolicyName: "{{ $.Values.resourceName }}-{{ $.Values.resourceType }}"
---
{{- end }}