apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: "{{ .Values.resourceName }}-{{ .Values.resourceType }}"
  namespace: {{ .Values.namespace }}
spec:
  # Add fields here
  authentication: 
    path: {{ .Values.authPath }}
    role: {{ .Values.authRole }}
    serviceAccount:
      name: {{ .Values.authSvcAcct }}
  passwordPolicy: |
    length = 20
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }
      rule "charset" {
        charset = "!@#$%^&*"
        min-chars = 1
      } 