default: 
  image: 
    name: ghcr.io/pm4ml/k3sbootstrap:0.10.12
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval `ssh-agent`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$GITHUB_SSH_KEY" | tr -d '\r' | ssh-add -
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - mkdir -p ~/.aws && echo "$AWS_CONFIG_FILE" >> ~/.aws/credentials
    - if [ -d ./k3s-sync-dir ]; then cp -r ./k3s-sync-dir/. /k3s-boot; else echo "not local files to copy"; fi 
stages:
  - "Deploy k3s"
  - "Destroy"
  - "Deploy Platform"

Destroy k3s Cluster:
  stage: "Destroy"
  script:
    - export
    - cd /k3s-boot
    - make backend -- -auto-approve
    - make destroy -- -auto-approve
    - aws s3 rm --recursive s3://$BUCKET/$PM4ML_ENVIRONMENT
  when: manual

Create k3s Cluster:
  stage: "Deploy k3s"
  script:
    - export
    - cd /k3s-boot
    - make backend -- -auto-approve
    - make apply -- -auto-approve
    - make k3s 
    - make kubeconfig
    - aws s3 cp /k3s-boot/kubeconfig s3://$BUCKET/$PM4ML_ENVIRONMENT/ --sse
    - aws s3 cp /k3s-boot/ssh-key s3://$BUCKET/$PM4ML_ENVIRONMENT/ --sse
    - aws s3 sync s3://$BUCKET/$PM4ML_ENVIRONMENT/ /k3s-boot/k3ss3 --sse
    - cp -r /k3s-boot/k3ss3/* /k3s-boot/ 
    - make wireguard
    - aws s3 sync /k3s-boot/wireguard.clients s3://$BUCKET/$PM4ML_ENVIRONMENT/wireguard.clients --sse
    - aws s3 cp /k3s-boot/wireguard.private.key s3://$BUCKET/$PM4ML_ENVIRONMENT/ --sse
    - aws s3 cp /k3s-boot/wireguard.public.key s3://$BUCKET/$PM4ML_ENVIRONMENT/ --sse
    - if [ ! -f /k3s-boot/vault-keys.json ]; then make vault; else echo "found vault, skipping make vault"; fi 
    - aws s3 cp /k3s-boot/vault-keys.json s3://$BUCKET/$PM4ML_ENVIRONMENT/ --sse
  when: manual

Install PM4MLs:
  stage: "Deploy Platform"
  script:
    - aws s3 cp s3://$BUCKET/$PM4ML_ENVIRONMENT/ssh-key /k3s-boot/ssh-key --sse
    - chmod 400 /k3s-boot/ssh-key
    - cd /k3s-boot
    - make backend -- -auto-approve
    - make apply -- -auto-approve
    - make pm4ml
    - aws s3 sync /k3s-boot/pm4ml-certoutput s3://$BUCKET/$PM4ML_ENVIRONMENT/pm4ml-certoutput --sse
  when: manual