apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: "{{ .Values.resourceName }}-{{ .Values.resourceType }}"
  namespace: {{ .Values.namespace }}
spec:
  # Add fields here
  authentication: 
    path: {{ .Values.authPath }}
    role: {{ .Values.authRole }}
    serviceAccount:
      name: {{ .Values.authSvcAcct }}
  passwordPolicy: {{ .Values.secretPasswordPolicy | toYaml | indent 1 }}