{{- range $ns := $.Values.secretNamespaces }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $.Values.secretName }}
  namespace: {{ $ns }}
spec:
  refreshPeriod: 1m0s
  vaultSecretDefinitions:
{{- range $key, $value := $.Values.secretKeyMap }}
    - authentication:
        path: {{ $.Values.authPath }}
        role: {{ $.Values.authRole }}
        serviceAccount:
          name: {{ $.Values.authSvcAcct }}
      name: dynamicsecret_{{ $key | replace "-" "_" }}
      path: "{{ $.Values.vaultBasePath }}/{{ $.Values.resourceName }}/{{ $.Values.secretName }}-{{ $key }}"
{{- end }}
  output:
    name: {{ $.Values.secretName }}
    stringData:
{{- range $key, $value := $.Values.secretKeyMap }}
      {{ $key }}: '{{ $value }}'
{{- end }}
    type: Opaque
---
{{- end }}