include:
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7/gitlab_templates/gitlab_ci_templates/.gitlab-main-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7/gitlab_templates/gitlab_ci_templates/.gitlab-ops-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7/gitlab_templates/gitlab_ci_templates/.gitlab-tests-ci.yml'

variables:
  GIT_SSL_NO_VERIFY: "true"
  PLATFORM_IAC_IMAGE_VERSION: "2.1.7"
  K3S_IAC_IMAGE_VERSION: "v0.18.0-snapshot.1"