include:
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7-beta1/gitlab_templates/switch-iac/.gitlab-main-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7-beta1/gitlab_templates/switch-iac/.gitlab-ops-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v2.1.7-beta1/gitlab_templates/switch-iac/.gitlab-tests-ci.yml'

variables:
  GIT_SSL_NO_VERIFY: "true"
  PLATFORM_IAC_IMAGE_VERSION: "2.1.7-beta1"
  K3S_IAC_IMAGE_VERSION: "0.17.0"