include:
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v4.1.0/gitlab_templates/gitlab_ci_templates/.gitlab-main-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v4.1.0/gitlab_templates/gitlab_ci_templates/.gitlab-ops-ci.yml'
  - remote: 'https://raw.githubusercontent.com/mojaloop/iac-aws-platform/v4.1.0/gitlab_templates/gitlab_ci_templates/.gitlab-tests-ci.yml'


variables:
  GIT_SSL_NO_VERIFY: "true"
  PLATFORM_IAC_IMAGE_VERSION: "4.1.0"
  K3S_IAC_IMAGE_VERSION: "0.19.0"